In [1]:
import numpy as np 
import pandas as pd

### **(1)Creating a DataFrame**

In [2]:
#there are two ways to create dataframe by using multiple lists and by using Dictionary

In [3]:
#(a)Creating dataframe by using dictionary
data={
    'Name':['Vishal','Aman','Nikhil','Sumit'],
    'Age':[23,23,21,22],
    'City':['Mumbai','New york','Paris','London'],
    'Salary':[89000,60000,80000,81000]
}
df=pd.DataFrame(data)
df

     Name  Age      City  Salary
0  Vishal   23    Mumbai   89000
1    Aman   23  New york   60000
2  Nikhil   21     Paris   80000
3   Sumit   22    London   81000

In [4]:
#(b)Creating data frame by using multuple lists 
my_list=[
    ['Vishal',23,'Mumbai',89000],
    ['Aman',23,'New york',60000],
    ['Nikhil',21,'Paris',80000],
    ['Sumit',22,'London',81000]
] 
df2=pd.DataFrame(my_list)
df2   #we got the dataframe but with deafult index and column name

        0   1         2      3
0  Vishal  23    Mumbai  89000
1    Aman  23  New york  60000
2  Nikhil  21     Paris  80000
3   Sumit  22    London  81000

In [5]:
#here we will create two more list for index and column name and then set them into dataframe
ind=[1,2,3,4]
col_names=['Name','Age','City','Monthly Savings']
df2=pd.DataFrame(my_list,index=ind,columns=col_names)
df2

     Name  Age      City  Monthly Savings
1  Vishal   23    Mumbai            89000
2    Aman   23  New york            60000
3  Nikhil   21     Paris            80000
4   Sumit   22    London            81000

### **(2)Selection And Indexing of Columns**

In [6]:
df2

     Name  Age      City  Monthly Savings
1  Vishal   23    Mumbai            89000
2    Aman   23  New york            60000
3  Nikhil   21     Paris            80000
4   Sumit   22    London            81000

In [7]:
#for selecting any one column 
df2['City']

1      Mumbai
2    New york
3       Paris
4      London
Name: City, dtype: object

In [8]:
#for selecting multiple columns
df2[['Age','City']]

   Age      City
1   23    Mumbai
2   23  New york
3   21     Paris
4   22    London

### **(3)Creating new Column inside dataframe**

In [9]:
#let we want add a column for designation of each person
df2['Designation']=['Data Scientist','unkown','Data Scientist','Engeneer']
df2

     Name  Age      City  Monthly Savings     Designation
1  Vishal   23    Mumbai            89000  Data Scientist
2    Aman   23  New york            60000          unkown
3  Nikhil   21     Paris            80000  Data Scientist
4   Sumit   22    London            81000        Engeneer

### **(4)Removing Columns**

In [10]:
#for removing any column we use .drop(col_name,index=0/1,inplace=True/False)
#if we put only column name then it will throw error as defalt axis is zero=row wise remove
#if we dont write inplace=True then it will just show an example output not change in original datafarme

In [11]:
#exaple1
df2.drop('Designation',axis=1)  #axis=1 for column and axis=0 for row

     Name  Age      City  Monthly Savings
1  Vishal   23    Mumbai            89000
2    Aman   23  New york            60000
3  Nikhil   21     Paris            80000
4   Sumit   22    London            81000

In [12]:
df2  #as you can see in original dataframe desihgnation not removed

     Name  Age      City  Monthly Savings     Designation
1  Vishal   23    Mumbai            89000  Data Scientist
2    Aman   23  New york            60000          unkown
3  Nikhil   21     Paris            80000  Data Scientist
4   Sumit   22    London            81000        Engeneer

In [13]:
#example2
df2.drop('Designation',axis=1,inplace=True)  #now this will permanently delete the column
df2

     Name  Age      City  Monthly Savings
1  Vishal   23    Mumbai            89000
2    Aman   23  New york            60000
3  Nikhil   21     Paris            80000
4   Sumit   22    London            81000

In [18]:
#example3
df2.drop(["Age","City"],axis=1,inplace=True)  #for deleting multiple columns
df2

     Name  Monthly Savings
1  Vishal            89000
2    Aman            60000
3  Nikhil            80000
4   Sumit            81000

### **(5)For Selcting Rows**

In [29]:
ind=[1,2,3,4]
df1=pd.DataFrame(data,index=ind)

In [37]:
df1

     Name  Age      City  Salary
1  Vishal   23    Mumbai   89000
2    Aman   23  New york   60000
3  Nikhil   21     Paris   80000
4   Sumit   22    London   81000

In [31]:
#for selecting row by using .loc (this selscting row by index given in dataframe)
df1.loc[1]

Name      Vishal
Age           23
City      Mumbai
Salary     89000
Name: 1, dtype: object

In [33]:
#by .iloc[] i.e.., default index based location(it selects row by default index like 0,1,2,3,....)
df1.iloc[1]

Name          Aman
Age             23
City      New york
Salary       60000
Name: 2, dtype: object

In [34]:
#for two rows
df1.loc[[1,2]]

     Name  Age      City  Salary
1  Vishal   23    Mumbai   89000
2    Aman   23  New york   60000

### **(6)Selection of subset of rows and column**

In [39]:
#example1- 1:2Bycity:salary
df1.loc[[1,2]][['City','Salary']]

       City  Salary
1    Mumbai   89000
2  New york   60000

In [40]:
#example2-want row=2,4 and col=name, city, salary
df1.loc[[2,4]][['Name',"City",'Salary']]

    Name      City  Salary
2   Aman  New york   60000
4  Sumit    London   81000

### **(7)Conditional Selection**

In [42]:
#for one condition
#example- give the data of those people whoose age is greater than 21
df1[df1['Age']>21]

     Name  Age      City  Salary
1  Vishal   23    Mumbai   89000
2    Aman   23  New york   60000
4   Sumit   22    London   81000

In [44]:
#For multiple condition
#example2-1st condition and city must be London
df1[(df1['Age']>21) & (df1['City']=='London')]

    Name  Age    City  Salary
4  Sumit   22  London   81000