In [1]:
import numpy as np 
import pandas as pd

### **(A)Finding Missing Data**

In [3]:
data={
    'A':[1,2,3,np.nan,5],
    'B':[np.nan,2,3,4,6],
    'C':[2,3,5,4,7],
    'D':[np.nan,np.nan,2,3,np.nan]
}
df=pd.DataFrame(data)
df

     A    B  C    D
0  1.0  NaN  2  NaN
1  2.0  2.0  3  NaN
2  3.0  3.0  5  2.0
3  NaN  4.0  4  3.0
4  5.0  6.0  7  NaN

In [4]:
#to find missing data we use .isna()
df.isna()

       A      B      C      D
0  False   True  False   True
1  False  False  False   True
2  False  False  False  False
3   True  False  False  False
4  False  False  False   True

In [5]:
#as above you can see the null values gives TRUE
#now we want to calculte how many null values are there in each column
#for this sort data counting manually is possible but what about for 1000 rows
#for this we use .sum() after .isna()
df.isna().sum()

A    1
B    1
C    0
D    3
dtype: int64

In [6]:
#if want to know if there are any blank cell or any type of null values in each column then
#we use .any()
df.isna().any()

A     True
B     True
C    False
D     True
dtype: bool

### **(B)Removing missing Data**

In [7]:
df

     A    B  C    D
0  1.0  NaN  2  NaN
1  2.0  2.0  3  NaN
2  3.0  3.0  5  2.0
3  NaN  4.0  4  3.0
4  5.0  6.0  7  NaN

In [8]:
#for removing null values we use .dropna() but it removes whole row if it contains any null values
#but we can use threshold to to control the removal 
#likr threshold=3 (means it will remove all the row which has less than 3 real values)

#example1-without threshold
df.dropna()

     A    B  C    D
2  3.0  3.0  5  2.0

In [9]:
#example2-with threshold
df.dropna(thresh=3)

     A    B  C    D
1  2.0  2.0  3  NaN
2  3.0  3.0  5  2.0
3  NaN  4.0  4  3.0
4  5.0  6.0  7  NaN

In [10]:
#as above you can see only first row got removed as thresh=3
#all above things didnt change original dataframe as we had not added inplace=TRUE

### **(C)Filling The Missing DATA**

In [11]:
df

     A    B  C    D
0  1.0  NaN  2  NaN
1  2.0  2.0  3  NaN
2  3.0  3.0  5  2.0
3  NaN  4.0  4  3.0
4  5.0  6.0  7  NaN

In [13]:
#if we want to replace na values to any number we can by this way
df.fillna(0)  #but this is only for display if really want to change in data put inplace=TRUE

     A    B  C    D
0  1.0  0.0  2  0.0
1  2.0  2.0  3  0.0
2  3.0  3.0  5  2.0
3  0.0  4.0  4  3.0
4  5.0  6.0  7  0.0

In [14]:
#If we want to fill column wise different values we can do by this way
values={'A':100,'B':200,'C':300,'D':400}
df.fillna(value=values)

       A      B  C      D
0    1.0  200.0  2  400.0
1    2.0    2.0  3  400.0
2    3.0    3.0  5    2.0
3  100.0    4.0  4    3.0
4    5.0    6.0  7  400.0

In [15]:
#we also can replce na values with the mean of respective column
df.fillna(df.mean())

      A     B  C    D
0  1.00  3.75  2  2.5
1  2.00  2.00  3  2.5
2  3.00  3.00  5  2.0
3  2.75  4.00  4  3.0
4  5.00  6.00  7  2.5