In [2]:
import pandas as pd
import numpy as np

### **(A)Merging 2 DataFrames**

In [5]:
#DataFrame 1 for Employee details
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'Name':['Vishal','Sumit','Vipin','Abhishek','Avs'],
    'department':['IT','HR','Finance','HR','IT']
}
)
#DataFrame 2 for SAlary information
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[89000,82000,70000,80000,72000],
    'bonus':[10000,5000,8000,1000,6000]
})

In [6]:
employees

   employee_id      Name department
0            1    Vishal         IT
1            2     Sumit         HR
2            3     Vipin    Finance
3            4  Abhishek         HR
4            5       Avs         IT

In [7]:
salaries

   employee_id  salary  bonus
0            1   89000  10000
1            2   82000   5000
2            3   70000   8000
3            6   80000   1000
4            7   72000   6000

In [8]:
#now we want to show dataframe by combining both dataframe 
#in different ways

In [11]:
#show on valid valuse by combining both dataframes 
#we use two important parameters (df1,df2,....,on= ,how= )
pd.merge(employees,salaries)  #this is default 
                              #where on=matching column of both dataframe and
                              #how='inner' means only those rows which are intersection of both dataframes

   employee_id    Name department  salary  bonus
0            1  Vishal         IT   89000  10000
1            2   Sumit         HR   82000   5000
2            3   Vipin    Finance   70000   8000

In [15]:
pd.merge(employees,salaries,on='employee_id',how='inner') #now this is with how='inner'

   employee_id    Name department  salary  bonus
0            1  Vishal         IT   89000  10000
1            2   Sumit         HR   82000   5000
2            3   Vipin    Finance   70000   8000

In [19]:
#using how='outer'
#we are merging both Dataframes i.e..,unioin(showing all rows of both dataframes)
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id      Name department   salary    bonus
0            1    Vishal         IT  89000.0  10000.0
1            2     Sumit         HR  82000.0   5000.0
2            3     Vipin    Finance  70000.0   8000.0
3            4  Abhishek         HR      NaN      NaN
4            5       Avs         IT      NaN      NaN
5            6       NaN        NaN  80000.0   1000.0
6            7       NaN        NaN  72000.0   6000.0

In [20]:
#by using how='left'
#we are giving more preference to left dataframe i.e.., To employees
#means will show all the rows of left datafarme but including common entries based on emploee_id
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id      Name department   salary    bonus
0            1    Vishal         IT  89000.0  10000.0
1            2     Sumit         HR  82000.0   5000.0
2            3     Vipin    Finance  70000.0   8000.0
3            4  Abhishek         HR      NaN      NaN
4            5       Avs         IT      NaN      NaN

In [21]:
#by using how='right'
#we are giving more preference to right dataframe i.e.., To salaries
#means will show all the rows of right datafarme but including common entries based on emploee_id

pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id    Name department  salary  bonus
0            1  Vishal         IT   89000  10000
1            2   Sumit         HR   82000   5000
2            3   Vipin    Finance   70000   8000
3            6     NaN        NaN   80000   1000
4            7     NaN        NaN   72000   6000

### **(B)Concatination Of 2 DataFrames**

In [23]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [24]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [25]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [26]:
#Concatination means pasting dataframes horizontally or vertically 
#(like combining both beside or up to down)

In [28]:
#axis=0 is an default parameter
#by using this we can paste other datafarme vertically(row wise i.e.., below to first dataframe)
pd.concat([df1,df2],axis=0)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [30]:
#axis=1
#by using this we can paste other datafarme horizontalli(column wise i.e.., beside to first dataframe)
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### **(C)Joining 2 DataFrames**

In [31]:
df1=pd.DataFrame({
    'name':['Vishal','Sumit','Vipin']
},index=[1,2,3])
df1

     name
1  Vishal
2   Sumit
3   Vipin

In [32]:
df2=pd.DataFrame({
    'score':[85,80,90]
},index=[2,3,4])
df2

   score
2     85
3     80
4     90

In [33]:
#joining two dataframes means joining one dataframes column to other dataframe
#but here also use of how='inner' or how='outer'

In [36]:
#by how='inner' means intesection of both dataframe based on common entries 
#here common entries are index
df1.join(df2,how='inner')

    name  score
2  Sumit     85
3  Vipin     80

In [37]:
#by how='outer' means union of both dataframe based on common entries 
#here common entries are index
df1.join(df2,how='outer')

     name  score
1  Vishal    NaN
2   Sumit   85.0
3   Vipin   80.0
4     NaN   90.0