In [1]:
import numpy as np
import pandas as pd

### **(A)SOME BASIC DATAFRAME OPERATIONS**
*-here we are going to show basic methods as shape ,columns*

*-also some functions as like .info(),.describe()*

*-we'll even show use of broadcating*

In [4]:
df1=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [5]:
#use shape to show dimension of dataframe
df1.shape

(5, 3)

In [7]:
#use .columns to show all the column names
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [8]:
#use .info() to show all the information of dataframe
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [9]:
#use .describe() to show all aggregation functions value of each columns
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [11]:
#by boradcasting add 10 to B column
df1['B']=df1['B']+10
df1

   A   B    C
0  1  30  100
1  2  40  200
2  3  50  300
3  4  60  400
4  5  70  500

### **(B)APPLY OPERATION**
*- used as .apply(fun_) and by using this we can apply any function to change values of any column*

**Q.change column B by squres of them**

In [16]:
#Basic use like by defining an function
def square(x):
    return x**2

df1['B'].apply(square)

0     900
1    1600
2    2500
3    3600
4    4900
Name: B, dtype: int64

In [17]:
df1

   A   B    C
0  1  30  100
1  2  40  200
2  3  50  300
3  4  60  400
4  5  70  500

In [18]:
#as above u can see that in original dataframe changes not taken placed
#below is an example how to do it
df1['B']=df1['B'].apply(square)
df1

   A     B    C
0  1   900  100
1  2  1600  200
2  3  2500  300
3  4  3600  400
4  5  4900  500

In [21]:
#advance way is by using lambda function instead of defining function , but now we will do A
df1['A']=df1['A'].apply(lambda x:x**2)
df1

     A     B    C
0    1   900  100
1   16  1600  200
2   81  2500  300
3  256  3600  400
4  625  4900  500